export const CORE_DB_MIGRATIONS = [
  `ALTER TABLE providers ADD COLUMN apiKeyEnv TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE providers ADD COLUMN apiKey TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE providers ADD COLUMN defaultCostPerImage REAL`,
  `ALTER TABLE jobs ADD COLUMN reviewMark TEXT DEFAULT ''`,
  `ALTER TABLE image_assets ADD COLUMN originalPath TEXT`,
  `ALTER TABLE image_assets ADD COLUMN processedPath TEXT`,
  `ALTER TABLE image_assets ADD COLUMN originalWidth INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN originalHeight INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN processedWidth INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN processedHeight INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN originalSizeBytes INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN processedSizeBytes INTEGER`,
  `ALTER TABLE image_assets ADD COLUMN preprocessingEnabled INTEGER DEFAULT 1`,
  `ALTER TABLE jobs ADD COLUMN providerTaskId TEXT`,
  `ALTER TABLE jobs ADD COLUMN providerStatus TEXT`,
  `ALTER TABLE jobs ADD COLUMN providerRawResponse TEXT`,
  `ALTER TABLE jobs ADD COLUMN submittedAt TEXT`,
  `ALTER TABLE jobs ADD COLUMN lastPolledAt TEXT`,
  `ALTER TABLE jobs ADD COLUMN pollCount INTEGER DEFAULT 0`,
  `ALTER TABLE jobs ADD COLUMN remoteImageUrl TEXT`,
  `ALTER TABLE projects ADD COLUMN runId TEXT`,
  `ALTER TABLE jobs ADD COLUMN postprocessTarget TEXT`,
  `ALTER TABLE jobs ADD COLUMN parentJobId TEXT`,
  `ALTER TABLE jobs ADD COLUMN revision INTEGER DEFAULT 0`,
  `ALTER TABLE projects ADD COLUMN referenceGuidanceMode TEXT NOT NULL DEFAULT 'preserve_subject'`,
  `ALTER TABLE jobs ADD COLUMN referenceGuidanceMode TEXT NOT NULL DEFAULT 'preserve_subject'`,
  `ALTER TABLE projects ADD COLUMN timeoutMs INTEGER NOT NULL DEFAULT 600000`,
  `ALTER TABLE projects ADD COLUMN workflowType TEXT NOT NULL DEFAULT 'legacy_batch_edit'`,
  `ALTER TABLE projects ADD COLUMN productName TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN productCode TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN productCategory TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN scenePrompt TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN shotPrompt TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN targetAudience TEXT DEFAULT ''`,
  `ALTER TABLE projects ADD COLUMN scriptTone TEXT DEFAULT '种草'`,
  `ALTER TABLE projects ADD COLUMN scriptPlatform TEXT DEFAULT '通用'`,
  `ALTER TABLE projects ADD COLUMN sellingPointsJson TEXT DEFAULT '[]'`,
  `ALTER TABLE projects ADD COLUMN sellingPointAnalysisJson TEXT DEFAULT ''`,
  `ALTER TABLE image_assets ADD COLUMN usage TEXT DEFAULT ''`,
  `UPDATE providers SET type = 'packy-images' WHERE baseUrl LIKE '%packyapi.com%' AND model = 'gpt-image-2' AND type = 'openai-compatible'`,
  `UPDATE providers SET type = 'packy-gemini-image' WHERE baseUrl LIKE '%packyapi.com%' AND model IN ('gemini-3.1-flash-image-preview', 'gemini-3-pro-image-preview')`,
  `UPDATE video_providers SET defaultModel = 'kling-v3' WHERE id = 'kling-3' AND defaultModel IN ('kling-3.0', 'kling-v3.0-i2v', 'kling-v3-0')`,
  `UPDATE video_providers SET defaultModel = 'doubao-seedance-2-0-260128' WHERE id = 'jimeng-2' AND defaultModel = 'jimeng-2.0'`,
  `INSERT OR IGNORE INTO video_providers (id, name, type, baseUrlEnv, apiKeyEnv, modelEnv, defaultModel, enabled, defaultDurationSec) VALUES ('kling-2-5', '可灵 2.5', 'kling', 'KLING_VIDEO_BASE_URL', 'KLING_VIDEO_API_KEY', 'KLING_2_5_VIDEO_MODEL', 'kling-v2-5-turbo', 1, 5)`,
  `ALTER TABLE video_providers ADD COLUMN baseUrl TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE video_providers ADD COLUMN apiKey TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE video_providers ADD COLUMN accessKey TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE video_providers ADD COLUMN secretKey TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN type TEXT NOT NULL DEFAULT 'openai-compatible'`,
  `ALTER TABLE script_providers ADD COLUMN apiStyle TEXT NOT NULL DEFAULT 'openai-compatible'`,
  `ALTER TABLE script_providers ADD COLUMN baseUrl TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN apiKey TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN model TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN keyEnv TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN baseUrlEnv TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN modelEnv TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN defaultBaseUrl TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN defaultModel TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE script_providers ADD COLUMN maxTokens INTEGER NOT NULL DEFAULT 8192`,
  `ALTER TABLE script_providers ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1`,
  `ALTER TABLE script_providers ADD COLUMN isBuiltin INTEGER NOT NULL DEFAULT 1`,
];
