import assert from 'node:assert/strict';
import fs from 'node:fs';

const panel = fs.readFileSync('components/mixcut/MixcutPanel.tsx', 'utf8');
const sidebar = fs.readFileSync('components/mixcut/MixcutSidebar.tsx', 'utf8');
const materialStep = fs.readFileSync('components/mixcut/MaterialStep.tsx', 'utf8');
const creationStep = fs.readFileSync('components/mixcut/CreationStep.tsx', 'utf8');
const previewStep = fs.readFileSync('components/mixcut/PreviewStep.tsx', 'utf8');
const timeline = fs.readFileSync('components/mixcut/MixcutTimeline.tsx', 'utf8');
const exportStep = fs.readFileSync('components/mixcut/ExportStep.tsx', 'utf8');
const styles = fs.readFileSync('components/mixcut/MixcutPanel.module.css', 'utf8');
const page = fs.readFileSync('app/projects/[id]/page.tsx', 'utf8');
const workbenchTabs = fs.readFileSync('components/ProjectWorkbenchTabs.tsx', 'utf8');

assert.doesNotMatch(page, /searchParams\.get\('mixcut'\)|showMixcutV1|FinalEditPanel/, 'Phase 7 必须移除查询参数灰度和旧第五步表面');
assert.match(page, /<MixcutPanel projectId=/, '项目页必须挂载真实 MixcutPanel');
assert.match(workbenchTabs, /id: 'final-edit', label: '智能混剪'/, '正式第五步标签必须切换为智能混剪');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/context/, 'MixcutPanel 必须读取真实 context API');
assert.match(panel, /AbortController/, '快速切组必须取消旧请求，防止迟到响应覆盖当前组');
assert.match(panel, /initializeMaterialSelection/, '素材默认选择必须通过按 shotSetId 隔离的领域函数');
assert.match(panel, /materialSelectionForShotSet/, '渲染素材选择时必须只读取当前 shotSetId');
assert.match(panel, /performShotSetSwitch[\s\S]{0,800}setSelectionByShotSet\(\{\}\)/, '真正切组时必须立即清空旧组选择');
assert.match(panel, /externalByShotSet/, '外部素材必须按 shotSetId 分桶保存');
assert.match(panel, /targetShotSetId/, '上传开始时必须捕获目标分镜组，切组后不能把响应合并到当前组');
assert.match(panel, /finally\s*{[\s\S]*refreshExternalAssets\(targetShotSetId\)/, '导入接口失败时也必须刷新目标组，展示后端已经落库的失败卡片');
assert.match(panel, /targetShotSetName/, '导入完成提示必须绑定上传开始时的目标组，不能误称后来切换的新组');
assert.match(panel, /external:\$\{asset\.id\}/, '外部素材必须使用 namespaced asset key');
assert.match(panel, /data-mixcut-shot-set-id/, '正式表面必须暴露当前分镜组供浏览器门禁验证');
assert.match(sidebar, /succeededVideoCount/);
assert.match(sidebar, /totalDurationUs/);
assert.match(sidebar, /其他分镜组不会混入/, '左辅栏必须明确当前组隔离规则');
assert.match(materialStep, /source === 'module4'/, '模块 4 素材必须显示真实来源标记');
assert.match(materialStep, /\.mp4,.mov,.avi,.webm/, '外部素材入口只接受 V1 锁定的视频格式');
assert.match(materialStep, /multiple/, '文件选择必须支持批量导入');
assert.match(materialStep, /onDrop=/, '外部素材入口必须支持拖拽导入');
assert.match(materialStep, /onDragOver=/, '拖拽区必须显式允许放置文件');
assert.match(materialStep, /aria-live="polite"/, '文件过滤和拖拽状态必须向辅助技术播报');
assert.match(materialStep, /SUPPORTED_VIDEO_EXTENSIONS/, '拖拽和文件选择必须共用明确的视频扩展名白名单');
assert.doesNotMatch(materialStep, /JPG|PNG|图片/, 'V1 已否决静态图片导入，正式 MaterialStep 不得重新出现图片入口');
assert.match(materialStep, /当前组还没有可用视频/, '空分镜组必须显示明确阻断提示');
assert.match(styles, /min-width:\s*0/, '主工作区 grid child 必须允许收缩，避免文字和卡片越界');
assert.match(styles, /overflow-y:\s*auto/, '素材区必须可独立滚动');
assert.match(panel, /<CreationStep/, 'Phase 2 必须挂载真实智能创作步骤');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/start/, '生成必须进入持久化 prepare job');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/draft/, '首次生成前必须有服务端草稿保存入口');
assert.match(panel, /type:\s*'set_mixcut_script_state'/, '文案、素材和音色修改必须通过 group command 落库');
assert.match(panel, /expectedRevision:\s*currentGroup\.revision/, '自动保存必须带 expectedRevision，不得 last-write-wins');
assert.match(panel, /markScriptSaved/, '服务端保存成功后才能清除未保存状态');
assert.match(panel, /group\.status === 'editing'/, '自动保存只能继续修改专用 editing group，不得改写已生成成片组');
assert.match(panel, /setSelectionByShotSet\(\(current\) => latestGroup[\s\S]{0,160}\{ \[currentShotSetId\]: persistedSelection \}/, '服务端已保存空选择时刷新不得重置为默认全选');
assert.match(panel, /const editedText = groupScript \? groupScript\.editedNarrationText : importedText/, '服务端已保存空文案时刷新不得回退为导入稿');
assert.match(panel, /\/api\/final-edit-jobs\/\$\{activeJobId\}/, '进度必须读取真实 job API');
assert.match(panel, /selectedMaterialKeys:\s*selectedIds/, '任务快照必须冻结当前素材选择');
assert.match(panel, /submittingRef\.current/, '生成提交必须有同步锁，防止快速双击重复计费');
assert.match(panel, /startRequestRef\.current\?\.sequence/, '生成响应必须校验请求 token，防止跨组迟到回填');
assert.match(panel, /disabled=\{loading \|\| submitting\}/, '生成 POST 未返回前必须禁止切组，避免丢失已创建任务的身份');
assert.match(panel, /persistVersionRef\.current > lastSavedVersionRef\.current[\s\S]{0,120}setPendingShotSetId/, '任何未保存文案、素材或音色都必须阻止直接切组');
assert.match(panel, /beforeunload/, '刷新或关闭页面前必须冲刷并保护待保存状态');
assert.match(creationStep, /保留修改并切换/);
assert.match(creationStep, /放弃修改并切换/);
assert.match(creationStep, /取消/, '脚本切换必须有保留、放弃、取消三路决策');
assert.match(creationStep, /恢复导入版本/);
assert.match(creationStep, /role="progressbar"/);
assert.match(creationStep, /analyzing[\s\S]*synthesizing[\s\S]*duration_check[\s\S]*matching[\s\S]*previewing/, '真实 TTS 后必须显示独立的时长校验阶段');
assert.match(creationStep, /job\?\.status === 'needs_input'/, 'duration review 必须作为可恢复状态展示，不能伪装成失败');
assert.match(creationStep, /目标总时长[\s\S]*实际总时长[\s\S]*偏差[\s\S]*容差/, '时长 review 必须展示完整的可行动数据');
assert.match(creationStep, /智能贴合时长/);
assert.match(creationStep, /修改文案或语速后重试/);
assert.match(creationStep, /按实际时长继续/);
assert.match(creationStep, /smartFitAvailable/, '智能贴合只允许在服务端明确开放时触发');
assert.match(panel, /duration-resolution/, '三种时长处理动作必须进入统一服务端 resolution API');
assert.match(panel, /\['queued', 'running'\]\.includes\(activeJobStatus\)/, 'needs_input 必须停止轮询');
assert.match(creationStep, /provider\?\.configured/, '只显示口播供应商配置状态');
assert.match(creationStep, /min="0\.5" max="2" step="0\.1"/, '语速规格必须为 0.5–2.0，步进 0.1');
assert.doesNotMatch(creationStep, /apiKey\b/, '新界面不得读取或回显明文 API Key');
assert.match(styles, /\.field textarea\s*{[^}]*min-height:\s*1(?:2[8-9]|[3-9]\d)px/s, '口播文案区必须保留足够的可编辑高度');
assert.match(styles, /\.voiceGrid\s*{[^}]*grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(/s, '音色列表必须随容器宽度自动换列');
assert.match(panel, /useState<0 \| 1 \| 2 \| 3>/, 'Phase 6 必须把正式导出接入第四步');
assert.match(panel, /\/api\/final-edit-groups\/\$\{job\.groupId\}/, 'prepare 成功后必须按任务精确 groupId 加载草稿');
assert.match(panel, /<PreviewStep/, '正式 MixcutPanel 必须挂载 PreviewStep');
assert.match(panel, /\(\['3x4', '9x16'\] as const\)\.map/, '正式入口必须允许选择 V1 的 3:4 和 9:16 全局画幅');
assert.match(panel, /outputPreset,/, '所选画幅必须冻结到 prepare job，不能只改浏览器预览');
assert.match(panel, /activeStep === 2 \? \(/, '第三步必须由显式 activeStep 状态控制');
assert.match(creationStep, /onPreview/, 'prepare 成功态必须提供去预览调整入口');
assert.match(previewStep, /expectedRevision:\s*currentVariant\.revision/, '视频编辑必须读取队列执行时的最新 variant revision');
assert.match(previewStep, /expectedRevision:\s*currentGroup\.revision/, '字幕编辑必须读取队列执行时的最新 group revision');
assert.match(previewStep, /queueRef\.current\.then\(work, work\)/, '连续编辑必须进入串行 command 队列，不能在 busy 时静默丢弃');
assert.doesNotMatch(previewStep, /if\s*\(busy\)\s*return false/, '保存期间不得直接丢弃第二个编辑 command');
assert.match(previewStep, /\/api\/final-edit-groups\/\$\{groupId\}/, '冲突或刷新必须重新读取服务端 group 权威状态');
assert.match(previewStep, /<FinalEditPreview/, '正式第三步必须复用双 video/Web Audio 预览器');
assert.match(previewStep, /warningIssues/, '预览必须持续展示服务端返回的时长 override warning');
assert.match(previewStep, /<MixcutTimeline/, '正式第三步必须挂载可操作 Mixcut 时间轴');
assert.match(previewStep, /<StyleEditor/, '正式第三步必须提供字体、字号、颜色、描边和位置等全局字幕样式');
assert.match(timeline, /const PX_PER_SECOND = 60/, 'V2 时间轴必须使用冻结的 60 px/s 缩放并通过滚动容纳长内容');
assert.match(timeline, /overflow|timelineScroll/, '时间轴必须提供真实滚动容器');
assert.match(timeline, /reorder_clips/, '片段拖动排序必须只提交一个原子 command');
assert.match(timeline, /视频[\s\S]*字幕[\s\S]*口播[\s\S]*BGM/, '正式时间轴必须显示四条共享坐标轨');
assert.match(styles, /\.tlLabels\s*{[^}]*flex-shrink:\s*0/s, '轨道标签必须位于横向滚动容器外并保持可见');
assert.match(styles, /\.tlScroll\s*{[^}]*overflow-x:\s*auto/s, '正式时间轴必须允许横向滚动');
assert.deepEqual([...new Set([...panel.matchAll(/localStorage\.(?:getItem|setItem)\('([^']+)'/g)].map((match) => match[1]))], ['mixcut-layout-v2'], '浏览器 storage 只能保存无业务含义的布局偏好');
assert.doesNotMatch(previewStep, /localStorage|sessionStorage/, '正式编辑和运行态不得落浏览器 storage');
assert.match(panel, /<ExportStep/, '正式 MixcutPanel 必须挂载 ExportStep');
assert.match(exportStep, /导出并写回项目/);
assert.match(exportStep, /产品型号/);
assert.match(exportStep, /warningIssues/, '导出必须持续展示服务端返回的时长 override warning');
assert.match(exportStep, /\/api\/final-edit-variants\/\$\{encodeURIComponent\(variant\.id\)\}\/render/, '正式导出必须创建持久化 render job');

console.log('final-edit mixcut UI contract tests passed');
