import assert from 'node:assert/strict';
import fs from 'node:fs';

const panel = fs.readFileSync('components/mixcut/MixcutPanel.tsx', 'utf8');
const sidebar = fs.readFileSync('components/mixcut/MixcutSidebar.tsx', 'utf8');
const materialStep = fs.readFileSync('components/mixcut/MaterialStep.tsx', 'utf8');
const creationStep = fs.readFileSync('components/mixcut/CreationStep.tsx', 'utf8');
const previewStep = fs.readFileSync('components/mixcut/PreviewStep.tsx', 'utf8');
const bgmCardPath = 'components/mixcut/BgmCard.tsx';
const bgmCard = fs.existsSync(bgmCardPath) ? fs.readFileSync(bgmCardPath, 'utf8') : '';
const timeline = fs.readFileSync('components/mixcut/MixcutTimeline.tsx', 'utf8');
const narrationSpeedControl = fs.readFileSync('components/mixcut/NarrationPlaybackRateControl.tsx', 'utf8');
const finalPreview = fs.readFileSync('components/final-edit/FinalEditPreview.tsx', 'utf8');
const exportStep = fs.readFileSync('components/mixcut/ExportStep.tsx', 'utf8');
const styles = fs.readFileSync('components/mixcut/mixcut-content.module.css', 'utf8');
const shell = fs.readFileSync('components/mixcut/MixcutShell.tsx', 'utf8');
const workspace = fs.readFileSync('components/mixcut/MixcutWorkspace.tsx', 'utf8');
const page = fs.readFileSync('app/projects/[id]/page.tsx', 'utf8');
const workbenchTabs = fs.readFileSync('components/ProjectWorkbenchTabs.tsx', 'utf8');
const proposalRoute = fs.readFileSync('app/api/final-edit-variants/[id]/proposals/route.ts', 'utf8');

assert.doesNotMatch(page, /searchParams\.get\('mixcut'\)|showMixcutV1|FinalEditPanel/, 'Phase 7 必须移除查询参数灰度和旧第五步表面');
assert.match(page, /<MixcutWorkspace projectId=/, '项目页必须挂载智能混剪工作区');
assert.match(workspace, /<MixcutPanel \{\.\.\.props\} \/>/, '智能混剪工作区必须保留真实 MixcutPanel');
assert.match(workbenchTabs, /id: 'final-edit', label: '智能混剪'/, '正式第五步标签必须切换为智能混剪');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/context/, 'MixcutPanel 必须读取真实 context API');
assert.match(panel, /AbortController/, '快速切组必须取消旧请求，防止迟到响应覆盖当前组');
assert.match(panel, /initializeMaterialSelection/, '素材默认选择必须通过按 shotSetId 隔离的领域函数');
assert.match(panel, /materialSelectionForShotSet/, '渲染素材选择时必须只读取当前 shotSetId');
assert.match(panel, /performShotSetSwitch[\s\S]{0,800}setSelectionByShotSet\(\{\}\)/, '真正切组时必须立即清空旧组选择');
assert.match(panel, /externalByShotSet/, '外部素材必须按 shotSetId 分桶保存');
assert.match(panel, /targetShotSetId/, '上传开始时必须捕获目标分镜组，切组后不能把响应合并到当前组');
assert.match(panel, /finally\s*{[\s\S]*refreshExternalAssets\(targetShotSetId\)/, '导入接口失败时也必须刷新目标组，展示后端已经落库的失败卡片');
assert.match(panel, /targetShotSetName/, '导入完成提示必须绑定上传开始时的目标组，不能误称后来切换的新组');
assert.match(panel, /external:\$\{asset\.id\}/, '外部素材必须使用 namespaced asset key');
assert.match(panel, /data-mixcut-shot-set-id/, '正式表面必须暴露当前分镜组供浏览器门禁验证');
assert.match(sidebar, /succeededVideoCount/);
assert.match(sidebar, /totalDurationUs/);
assert.match(sidebar, /其他分镜组不会混入/, '左辅栏必须明确当前组隔离规则');
assert.match(materialStep, /source === 'module4'/, '模块 4 素材必须显示真实来源标记');
assert.match(materialStep, /\.mp4,.mov,.avi,.webm/, '外部素材入口只接受 V1 锁定的视频格式');
assert.match(materialStep, /\.gif/, '外部素材入口必须接受 GIF');
assert.match(materialStep, /GIF 会自动转为 MP4/, 'GIF 入口必须明确转码行为');
assert.match(materialStep, /matPreviewButton/, '素材卡必须提供视频预览入口');
assert.match(materialStep, /matPreviewAction/, '素材卡必须提供不依赖悬浮层的明确预览按钮');
assert.match(materialStep, /mixcut-material-card-preview/, '素材卡预览按钮必须有稳定的验证入口');
assert.match(materialStep, /role="dialog"/, '素材预览必须使用可访问对话框');
assert.match(materialStep, /multiple/, '文件选择必须支持批量导入');
assert.match(materialStep, /onDrop=/, '外部素材入口必须支持拖拽导入');
assert.match(materialStep, /onDragOver=/, '拖拽区必须显式允许放置文件');
assert.match(materialStep, /aria-live="polite"/, '文件过滤和拖拽状态必须向辅助技术播报');
assert.match(materialStep, /SUPPORTED_VIDEO_EXTENSIONS/, '拖拽和文件选择必须共用明确的视频扩展名白名单');
assert.doesNotMatch(materialStep, /JPG|PNG|图片/, 'V1 已否决静态图片导入，正式 MaterialStep 不得重新出现图片入口');
assert.match(materialStep, /当前组还没有可用视频/, '空分镜组必须显示明确阻断提示');
assert.match(styles, /min-width:\s*0/, '主工作区 grid child 必须允许收缩，避免文字和卡片越界');
assert.match(styles, /overflow-y:\s*auto/, '素材区必须可独立滚动');
assert.match(panel, /<CreationStep/, 'Phase 2 必须挂载真实智能创作步骤');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/start/, '生成必须进入持久化 prepare job');
assert.match(panel, /\/api\/projects\/\$\{projectId\}\/final-edit\/draft/, '首次生成前必须有服务端草稿保存入口');
assert.match(panel, /type:\s*'set_mixcut_script_state'/, '文案、素材和音色修改必须通过 group command 落库');
assert.match(panel, /expectedRevision:\s*currentGroup\.revision/, '自动保存必须带 expectedRevision，不得 last-write-wins');
assert.match(panel, /markScriptSaved/, '服务端保存成功后才能清除未保存状态');
assert.match(panel, /group\.status === 'editing'/, '自动保存只能继续修改专用 editing group，不得改写已生成成片组');
assert.match(panel, /setSelectionByShotSet\(\(current\) => latestGroup[\s\S]{0,160}\{ \[currentShotSetId\]: persistedSelection \}/, '服务端已保存空选择时刷新不得重置为默认全选');
assert.match(panel, /const editedText = groupScript \? groupScript\.editedNarrationText : importedText/, '服务端已保存空文案时刷新不得回退为导入稿');
assert.match(panel, /\/api\/final-edit-jobs\/\$\{activeJobId\}/, '进度必须读取真实 job API');
assert.match(proposalRoute, /videoJobNotRejectedSql\(db, ['"]vj['"]\)/, '自动补空隙不得重新选入已剔除视频');
assert.match(panel, /selectedMaterialKeys:\s*requestMaterialKeys/, '任务快照必须冻结当前素材选择或被选历史版本的素材快照');
assert.match(panel, /submittingRef\.current/, '生成提交必须有同步锁，防止快速双击重复计费');
assert.match(panel, /startRequestRef\.current\?\.sequence/, '生成响应必须校验请求 token，防止跨组迟到回填');
assert.match(panel, /disabled=\{loading \|\| submitting\}/, '生成 POST 未返回前必须禁止切组，避免丢失已创建任务的身份');
assert.match(panel, /persistVersionRef\.current > lastSavedVersionRef\.current[\s\S]{0,120}setPendingShotSetId/, '任何未保存文案、素材或音色都必须阻止直接切组');
assert.match(panel, /beforeunload/, '刷新或关闭页面前必须冲刷并保护待保存状态');
assert.match(creationStep, /保留修改并切换/);
assert.match(creationStep, /放弃修改并切换/);
assert.match(creationStep, /取消/, '脚本切换必须有保留、放弃、取消三路决策');
assert.match(creationStep, /恢复导入版本/);
assert.match(creationStep, /role="progressbar"/);
assert.match(creationStep, /analyzing[\s\S]*synthesizing[\s\S]*duration_check[\s\S]*matching[\s\S]*previewing/, '真实 TTS 后仍应记录实际时长，但不得变成人工审核');
assert.match(creationStep, /buildScriptDurationAdvisory/, '字数提示必须使用与脚本生成一致的时长预算');
assert.match(creationStep, /建议[\s\S]*字/, '文案卡必须展示目标时长对应的建议字数范围');
assert.match(creationStep, /仍可直接生成/, '超出建议字数只能软提醒，不得阻止生成');
assert.doesNotMatch(creationStep, /maxLength=/, '字数提醒不得变成 textarea 硬限制');
assert.match(creationStep, /disabled=\{busy \|\| Boolean\(startDisabledReason\)\}/, '生成按钮不得把字数超限作为禁用条件');
assert.doesNotMatch(creationStep, /真实口播时长需要确认|智能贴合时长|修改文案或语速后重试|按实际时长继续|onResolveDuration/, '正式界面必须移除真实时长三选一审核');
assert.match(panel, /duration-resolution[\s\S]{0,700}action:\s*'accept_actual'/, '旧版等待确认任务必须自动按实际时长恢复，不能再次要求用户操作');
assert.match(creationStep, /provider\?\.configured/, '只显示口播供应商配置状态');
assert.match(creationStep, /min="0\.5" max="2" step="0\.1"/, '语速规格必须为 0.5–2.0，步进 0.1');
assert.doesNotMatch(creationStep, /apiKey\b/, '新界面不得读取或回显明文 API Key');
assert.match(styles, /\.field textarea\s*{[^}]*min-height:\s*1(?:2[8-9]|[3-9]\d)px/s, '口播文案区必须保留足够的可编辑高度');
assert.match(styles, /\.voiceGrid\s*{[^}]*grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(/s, '音色列表必须随容器宽度自动换列');
assert.match(panel, /useState<0 \| 1 \| 2 \| 3>/, 'Phase 6 必须把正式导出接入第四步');
assert.match(panel, /\/api\/final-edit-groups\/\$\{job\.groupId\}/, 'prepare 成功后必须按任务精确 groupId 加载草稿');
assert.match(panel, /<PreviewStep/, '正式 MixcutPanel 必须挂载 PreviewStep');
assert.match(panel, /\(\['3x4', '9x16'\] as const\)\.map/, '正式入口必须允许选择 V1 的 3:4 和 9:16 全局画幅');
assert.match(panel, /outputPreset:\s*requestOutputPreset/, '所选画幅必须冻结到 prepare job，不能只改浏览器预览');
assert.match(panel, /activeStep === 2 \? \(/, '第三步必须由显式 activeStep 状态控制');
assert.match(creationStep, /onPreview/, 'prepare 成功态必须提供去预览调整入口');
assert.match(creationStep, /再生成一版/, 'prepare 成功态必须允许基于当前设置生成独立新版本');
assert.match(panel, /function isPreviewGroupReady[\s\S]{0,220}\['ready', 'partial'\][\s\S]{0,120}group\.variants\.length > 0/, '预览就绪规则必须同时校验 group 状态和真实 variant，不得只看 job succeeded');
assert.match(panel, /previewReady=\{isPreviewGroupReady\(preparedGroup\)\}/, '预览入口必须复用完整草稿就绪规则');
assert.match(creationStep, /disabled=\{submitting \|\| !previewReady\}/, '完整预览草稿尚未载入或正在重新提交时必须禁用预览入口');
assert.match(panel, /setRecentGroups\(\(current\) => \[completedGroup, \.\.\.current\.filter/, '新版本完成后必须立即进入最近会话');
assert.match(sidebar, /onSelectSession\(session\.id\)/, '最近会话必须按具体 groupId 切换，不能退化为只切 shotSetId');
assert.match(sidebar, /aria-current=\{session\.id === activeSessionId/, '最近会话必须标识当前打开的版本');
assert.match(panel, /draftGroupRef\.current = !selectedGroupId && editingGroup/, '打开历史会话后不得继续复用同分镜组的通用 editing 草稿');
assert.match(previewStep, /expectedRevision:\s*currentVariant\.revision/, '视频编辑必须读取队列执行时的最新 variant revision');
assert.match(previewStep, /expectedRevision:\s*currentGroup\.revision/, '字幕编辑必须读取队列执行时的最新 group revision');
assert.match(previewStep, /const targetGroupId = groupRef\.current\.id[\s\S]{0,240}currentGroup\.id !== targetGroupId/, '字幕命令入队时必须绑定目标组，切组后不得误写新组');
assert.match(previewStep, /queueRef\.current\.then\(work, work\)/, '连续编辑必须进入串行 command 队列，不能在 busy 时静默丢弃');
assert.doesNotMatch(previewStep, /if\s*\(busy\)\s*return false/, '保存期间不得直接丢弃第二个编辑 command');
assert.match(previewStep, /\/api\/final-edit-groups\/\$\{groupId\}/, '冲突或刷新必须重新读取服务端 group 权威状态');
assert.match(previewStep, /<FinalEditPreview/, '正式第三步必须复用双 video/Web Audio 预览器');
assert.match(previewStep, /previewModeTabs/, '预览调整必须提供独立的预览模式切换器');
assert.match(previewStep, /role="tablist"/, '预览模式切换器必须使用可访问的 Tab 语义');
assert.match(previewStep, /成片预览/, '预览调整必须提供成片预览模式');
assert.match(previewStep, /素材预览/, '预览调整必须提供素材预览模式');
assert.match(previewStep, /aria-label=\{`预览素材 \$\{asset\.filename\}`\}/, '素材调整列表必须提供独立预览按钮');
assert.match(previewStep, /data-testid="mixcut-material-preview"/, '素材预览模式必须暴露稳定的验证入口');
assert.match(previewStep, /<video[\s\S]{0,500}controls[\s\S]{0,500}muted[\s\S]{0,500}playsInline/, '素材预览模式必须直接提供可播放的视频控件');
assert.match(previewStep, /<BgmCard/, '背景音乐必须抽成可独立确认的卡片组件');
assert.match(bgmCard, /type="file"/, '背景音乐卡片必须提供本地音乐文件入口');
assert.match(bgmCard, /multiple/, '背景音乐卡片必须支持一次选择多首音乐');
assert.match(bgmCard, /\.mp3,.wav,.m4a,.aac,.flac,.ogg/i, '文件选择器必须提示已确认的音频格式');
assert.match(bgmCard, /添加音乐/, '背景音乐卡片必须显示添加音乐操作');
assert.match(bgmCard, /添加中…/, '添加期间必须显示进度状态并阻止重复提交');
assert.match(bgmCard, /onImportFiles/, 'BgmCard 必须接收正式导入回调');
assert.match(bgmCard, /track\.filename/, '下拉必须使用服务端可读 filename');
assert.doesNotMatch(bgmCard, />\{track\.relativePath\}</, '下拉不得直接渲染内部路径');
assert.match(bgmCard, /\/api\/final-edit-bgm\/\$\{encodeURIComponent\(selectedTrackId\)\}\/file/, '试听必须使用正式媒体接口');
assert.match(bgmCard, /试听/, '背景音乐卡片必须显示独立试听操作');
assert.match(bgmCard, /停止/, '试听中必须提供明确的停止状态');
assert.match(bgmCard, /audio\.volume = 1/, '独立试听必须使用原始音量');
assert.match(bgmCard, /audio\.currentTime = 0/, '停止试听必须归零');
assert.match(bgmCard, /stopRequestId/, 'BgmCard 必须支持外部停止请求');
assert.match(bgmCard, /active/, 'BgmCard 必须根据 active 状态停止播放');
assert.match(bgmCard, /scopeId/, '切组时 BgmCard 必须停止当前试听');
assert.match(bgmCard, /result\.outcome === 'applied'/, 'BgmCard 必须处理导入成功路径');
assert.match(bgmCard, /result\.outcome === 'imported'/, '切组后只能提示音乐已进入音乐库，不能谎报已经应用到音轨');
assert.match(bgmCard, /result\.announcement/, 'BgmCard 必须播报父组件提供的导入结果');
assert.match(bgmCard, /添加失败/, 'BgmCard 必须处理导入全部失败路径');
assert.match(bgmCard, /setTimeout/, '成功提示必须短暂显示后自动收起');
assert.match(bgmCard, /aria-live="polite"/, '选择文件后的状态必须可访问播报');
assert.doesNotMatch(bgmCard, /待导入|UI 样稿|确认后再导入/, '界面不能暴露内部导入阶段或二次确认');
assert.doesNotMatch(bgmCard, /URL\.createObjectURL/, '正式 BgmCard 不再使用本地样稿预览');
assert.match(styles, /\.bgmActions/, '背景音乐操作按钮必须有独立布局');
assert.match(styles, /\.bgmImportStatus/, '背景音乐样稿状态必须有独立样式');
assert.match(previewStep, /importBgmFiles/, 'PreviewStep 必须定义 BGM 导入函数');
assert.match(previewStep, /new FormData\(\)/, '导入必须使用 FormData 上传');
assert.match(previewStep, /formData\.append\('files'/, 'FormData 必须追加 files 字段');
assert.match(previewStep, /fetch\('\/api\/final-edit-bgm'/, '导入必须请求全局 BGM API');
assert.match(previewStep, /response\.status !== 422/, '422 必须视为合法部分失败响应');
assert.match(previewStep, /firstSuccessfulTrackId/, '导入后必须使用服务端首选曲目 ID');
assert.match(previewStep, /await reloadGroup\(targetGroupId\)/, '导入后必须先刷新成片组');
assert.match(previewStep, /type:\s*'set_bgm'/, '导入后必须自动切换 BGM');
assert.ok(
  previewStep.lastIndexOf('setMessage(errorMessages)') > previewStep.indexOf("const succeeded = await applyVariantNow({ type: 'set_bgm'"),
  '部分失败详情必须在 set_bgm 自动保存完成后发布，不能被“已自动保存”覆盖',
);
assert.match(previewStep, /previewStopRequestId/, '成片预览必须有外部停止指引');
assert.match(previewStep, /auditionStopRequestId/, '独立试听必须有外部停止指引');
assert.match(previewStep, /selectedBgmTrack/, 'PreviewStep 必须从当前 group 解析 BGM 曲目名称');
assert.match(finalPreview, /stopRequestId/, 'FinalEditPreview 必须接受外部停止请求');
assert.match(finalPreview, /onPlaybackStart/, 'FinalEditPreview 必须通知外部播放开始');
assert.match(timeline, /bgmTrackName/, '时间轴必须接收 BGM 曲目文件名');
assert.match(timeline, /无 BGM/, '时间轴无 BGM 时必须显示空状态');
assert.match(previewStep, /warningIssues/, '预览必须持续展示服务端返回的时长 override warning');
assert.match(
  timeline,
  /variant\.bgm\.trackId && bgmTrackName \? \([\s\S]{0,180}<Waveform tone="bgm"/,
  '只有真正选择 BGM 时才能渲染 BGM 波形',
);
assert.match(previewStep, /<MixcutTimeline/, '正式第三步必须挂载可操作 Mixcut 时间轴');
assert.match(previewStep, /type: 'set_narration_playback_rate'/, '口播轨变速必须保存到当前成片组，不能提升为新版本生成请求');
assert.doesNotMatch(previewStep, /onRegenerateWithSpeed/, '口播轨直接变速不得保留生成新版本回调');
assert.match(previewStep, /<StyleEditor/, '正式第三步必须提供字体、字号、颜色、描边和位置等全局字幕样式');
assert.match(timeline, /const PX_PER_SECOND = 60/, 'V2 时间轴必须使用冻结的 60 px/s 缩放并通过滚动容纳长内容');
assert.match(timeline, /overflow|timelineScroll/, '时间轴必须提供真实滚动容器');
assert.match(timeline, /reorder_clips/, '片段拖动排序必须只提交一个原子 command');
assert.match(timeline, /视频[\s\S]*字幕[\s\S]*口播[\s\S]*BGM/, '正式时间轴必须显示四条共享坐标轨');
assert.match(timeline, /type TimelineTool = 'select' \| 'split'/, '时间轴必须提供互斥的选择/分割工具状态');
assert.match(timeline, /aria-label="选择工具"[\s\S]*aria-label="分割工具"/, '时间轴工具栏必须按选择、分割顺序提供可访问按钮');
assert.match(timeline, /name="scissors"/, '分割工具必须复用统一剪刀图标');
assert.doesNotMatch(timeline, /↖/, '选择工具不得使用文本符号冒充图标');
assert.match(styles, /\.tlToolbar\s*{[^}]*flex-wrap:\s*wrap/s, '时间轴工具栏必须允许说明在窄宽度下换行');
assert.match(styles, /\.tlToolButton\s*{[^}]*flex:\s*0 0 auto[^}]*white-space:\s*nowrap/s, '选择和分割按钮不得被压缩或拆字');
assert.match(timeline, /planSubtitleCueSplit/, '字幕块点击分割必须复用可测试的切点和文字边界规划器');
assert.match(timeline, /type: 'split_subtitle_cue'/, '分割工具必须通过现有原子字幕 command 持久化');
assert.match(previewStep, /type: 'normalize_automatic_subtitles'/, '打开旧草稿时必须触发受保护的自动字幕空白重切命令');
assert.match(timeline, /\| \{ kind: 'subtitle'; cueId: string; x: number; y: number \}/, '时间线上下文菜单必须能绑定具体字幕 Cue');
assert.match(timeline, /onOpenContextMenu=\{\(clientX, clientY\) => setContextMenu\(\{[\s\S]{0,180}kind: 'subtitle'[\s\S]{0,120}cueId: cue\.id/, '字幕块必须把右键坐标和 Cue ID 传给共享菜单');
assert.match(timeline, /kind: 'subtitle'[\s\S]{0,140}cueId: cue\.id[\s\S]{0,100}x:\s*[\s\S]{0,80}clientX[\s\S]{0,100}y:\s*[\s\S]{0,80}clientY/, '字幕菜单状态必须以右键坐标写入 x 和 y，允许菜单位置受视口约束');
assert.match(timeline, /function SubtitleBlock[\s\S]{0,6000}onContextMenu=\{[\s\S]{0,160}onOpenContextMenu\(event\.clientX, event\.clientY\)/, 'SubtitleBlock 右键必须把原始 clientX/clientY 坐标传给共享菜单，不能由 VideoBlock 同形代码满足');
assert.match(timeline, /function SubtitleBlock[\s\S]{0,2400}const begin = \(mode: 'move' \| 'start' \| 'end', event: React\.PointerEvent<HTMLElement>\) => \{\s*if \(event\.button !== 0\) return;/, 'SubtitleBlock 裁剪和移动手柄必须先忽略非左键，避免右键进入裁剪');
assert.match(timeline, /contextMenu\.kind === 'narration' \? 'dialog' : 'menu'/, '视频和字幕使用 menu 语义，只有口播调速使用 dialog');
assert.match(timeline, /contextMenu\.kind === 'subtitle' \? '字幕操作'/, '字幕菜单必须提供独立可访问名称');
assert.match(timeline, /type: 'delete_subtitle_cue', cueId/, '字幕菜单必须通过现有原子 group command 持久化删除');
assert.match(timeline, /<NarrationPlaybackRateControl/, '口播音频轨必须复用共享倍速控件');
assert.match(narrationSpeedControl, /type="range"/, '口播变速必须使用 0.5x～2.0x 拉条，而不是平铺倍速按钮');
assert.match(narrationSpeedControl, /\$\{ariaLabelPrefix\}拉条/, '倍速拉条必须提供按使用位置区分的可访问名称');
assert.match(narrationSpeedControl, /type="number"/, '倍速拉条必须配套可精确输入的同步数值框');
assert.match(narrationSpeedControl, /\$\{ariaLabelPrefix\}数值/, '倍速数值框必须提供按使用位置区分的可访问名称');
assert.match(timeline, /onPreview=\{onNarrationPlaybackRatePreview\}/, '拖动倍速拉条必须立即更新当前预览音轨');
assert.match(timeline, /onCommit=\{onNarrationPlaybackRateCommit\}/, '松开倍速拉条必须自动保存当前音轨倍速');
assert.doesNotMatch(timeline, /生成.*新版本/, '口播音轨直接变速不得显示生成新版本操作');
assert.match(styles, /\.narrationSpeedPresets\s*{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/s, '右栏倍速快捷值必须使用四等分网格，不能挤成连续文字');
assert.match(finalPreview, /narration\.playbackRate = narrationPlaybackRate/, '成片预览必须把保存的倍速应用到真实 audio 元素');
assert.match(styles, /\.tlLabels\s*{[^}]*flex-shrink:\s*0/s, '轨道标签必须位于横向滚动容器外并保持可见');
assert.match(styles, /\.tlScroll\s*{[^}]*overflow-x:\s*auto/s, '正式时间轴必须允许横向滚动');
assert.match(shell, /localStorage\.getItem\(layoutStorageKey/, '布局读取必须使用专用布局 key');
assert.match(shell, /localStorage\.setItem\(layoutStorageKey/, '布局写入必须使用专用布局 key');
assert.match(shell, /layoutStorageKey = 'mixcut-layout-v2'/, '单条混剪布局必须使用固定的布局偏好 key');
assert.doesNotMatch(previewStep, /localStorage|sessionStorage/, '正式编辑和运行态不得落浏览器 storage');
assert.match(panel, /<ExportStep/, '正式 MixcutPanel 必须挂载 ExportStep');
assert.match(exportStep, /导出并写回项目/);
assert.match(exportStep, /产品型号/);
assert.match(exportStep, /warningIssues/, '导出必须持续展示服务端返回的时长 override warning');
assert.match(exportStep, /\/api\/final-edit-variants\/\$\{encodeURIComponent\(variant\.id\)\}\/render/, '正式导出必须创建持久化 render job');

console.log('final-edit mixcut UI contract tests passed');
