import assert from 'node:assert/strict';
import fs from 'node:fs';

const panel = fs.readFileSync(new URL('../components/ScriptPanel.tsx', import.meta.url), 'utf8');
const strategy = fs.readFileSync(new URL('../components/ScriptStrategyConfig.tsx', import.meta.url), 'utf8');
const result = fs.readFileSync(new URL('../components/ScriptResultView.tsx', import.meta.url), 'utf8');
const picker = fs.readFileSync(new URL('../components/ScriptTemplatePicker.tsx', import.meta.url), 'utf8');
const creativePackage = fs.readFileSync(new URL('../app/api/projects/[id]/creative-package/route.ts', import.meta.url), 'utf8');

assert.match(panel, /analyzed\.recommendedTemplate\.id/);
assert.match(panel, /parsed\.version === 2 && parsed\.shotSetId/);
assert.match(panel, /这份脚本由旧版本生成/, '未声明版本的历史草稿继续走既有只读提示路径');
assert.doesNotMatch(panel, /await loadShotImages\(selectedShotSetId\)/, 'V3 生成成功后不得加载分镜图片');
assert.match(strategy, /目标总时长（包含封面）/);
assert.match(strategy, /口播正文约/);
assert.match(strategy, /minContentCharacters/);
assert.match(strategy, /视觉生成模型/);
assert.match(strategy, /p\.supportsVision/);
assert.match(strategy, /发送给该模型进行视觉理解/);
assert.match(strategy, /人群匹配/);
assert.match(strategy, /平台匹配/);
assert.match(strategy, /卖点强度/);
assert.match(strategy, /历史策略分析不完整/);
assert.match(strategy, /v3AnalysisIsComplete/);
assert.match(panel, /p\.configured && p\.supportsVision/, '脚本生成模型必须默认选择已配置且支持视觉的供应商');
assert.match(panel, /getDefaultSelectedSellingPointKeys\(loadedAnalysis\)/, '加载 V3 分析时必须统一选择最终排名前三');
assert.match(panel, /getDefaultSelectedSellingPointKeys\(analyzed\)/, '新分析完成时必须统一选择最终排名前三');
assert.match(panel, /resolveSelectedSellingPoints\(analysis, selectedSellingPointKeys\)/, '生成入参必须通过稳定 ID 回填卖点，不能按标题猜测');
assert.match(panel, /spWithData\.length !== selectedSellingPointKeys\.length/, '历史选择键失效时必须阻止提交空或残缺卖点');
assert.match(strategy, /getSellingPointSelectionKey\(r\)/, '卖点勾选状态必须使用稳定 ID 作为身份键');
assert.match(panel, /hydrateStrategyFromDraft\(first, \{ restoreSellingPoints: false \}\)/, '初次加载最新草稿不得覆盖分析排名前三');
assert.doesNotMatch(panel, /filter\(\(ranking\) => ranking\.priority === 'highest'\)\.slice\(0, 1\)/, '不得退回只选择唯一 highest');
assert.match(panel, /script_material_mismatch/, '模板与图片不匹配时必须展示专用提示，不能误报为时长问题');
assert.match(panel, /data\.message \|\| data\.error/, '策略分析合同失败时必须优先展示服务端中文说明，而不是只显示错误码');
assert.match(panel, /请先填写目标人群/, '没有目标人群时必须在调用模型前阻止泛化分析');
assert.match(panel, /materialReason/, '素材不匹配提示必须展示模型给出的图片不足原因');
assert.match(panel, /unsupportedNarrativeBeats/, '素材不匹配提示必须说明模板中缺少画面承接的阶段');
assert.match(panel, /readScriptGenerationStream/, '正式脚本生成必须消费服务端真实进度流');
assert.match(panel, /role="progressbar"/, '生成中必须显示可访问的进度条');
assert.match(panel, /aria-valuenow=\{generationProgress\.percent\}/, '进度条必须暴露当前进度值');
assert.match(panel, /handleCancelGeneration/, '生成中必须提供取消处理器');
assert.match(panel, /取消生成/, '生成中必须显示取消按钮');
assert.match(result, /复制字幕稿/);
assert.match(result, /复制配音稿/);
assert.match(result, /完整字幕稿/);
assert.match(result, /完整配音稿（保留自然标点）/);
assert.match(result, /卖点采用情况/);
assert.match(result, /图片暂不支持/);
assert.match(result, /sellingPointUsage/);
assert.match(picker, /SCRIPT_TEMPLATES/);
assert.match(creativePackage, /manifestScript/);
assert.match(creativePackage, /fullSubtitle/);
assert.match(creativePackage, /if \(isV3\)/);

console.log('script v3 UI contract tests passed');
