import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import sharp from 'sharp';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'script-directory-test-'));
process.env.CREATIVE_STUDIO_DATA_ROOT = root;
const { importImageDirectory } = await import('../lib/script-studio/import-directory.ts');
const { tileSourceImages } = await import('../lib/script-studio/tiling.ts');
const db = new Database(':memory:');
db.exec(`CREATE TABLE projects (id TEXT PRIMARY KEY);
  INSERT INTO projects VALUES ('p1');
  CREATE TABLE image_assets (id TEXT PRIMARY KEY, projectId TEXT, role TEXT, filename TEXT, path TEXT, originalPath TEXT,
    mimeType TEXT, originalWidth INTEGER, originalHeight INTEGER, originalSizeBytes INTEGER, preprocessingEnabled INTEGER, usage TEXT, createdAt TEXT);`);
const folder = path.join(root, '输入 含空格');
await fs.mkdir(folder);
const png = await sharp({ create: { width: 1200, height: 800, channels: 3, background: '#abcdef' } }).png().toBuffer();
for (const name of ['图片10.png', '图片2.png', '图片1.png']) await fs.writeFile(path.join(folder, name), png);
await fs.writeFile(path.join(folder, 'Thumbs.db'), 'ignore');
await fs.mkdir(path.join(folder, '子文件夹'));
await fs.writeFile(path.join(folder, '子文件夹', '图片0.png'), png);
const imported = await importImageDirectory(db, 'p1', `"${folder}"`);
assert.deepEqual(imported.files.map((file) => file.filename), ['图片1.png', '图片2.png', '图片10.png']);
assert.equal(imported.files.length, 3);
const original = db.prepare('SELECT originalPath FROM image_assets WHERE id = ?').get(imported.files[0]!.id) as { originalPath: string };
assert.deepEqual(await fs.readFile(original.originalPath), png, '导入不能重编码');
assert.deepEqual(await fs.readFile(path.join(folder, '图片1.png')), png, '原图不得改变');
const tiled = await tileSourceImages(db, 'p1', imported.files.map((file) => file.id), { directVision: true });
assert.equal(tiled.totalTiles, 3);
assert.equal(tiled.pages[0]!.tiles[0]!.mimeType, 'image/png');
assert.deepEqual(Buffer.from(tiled.pages[0]!.tiles[0]!.imageBase64, 'base64'), png, '合适的裁切图直接交付原字节');
await assert.rejects(() => importImageDirectory(db, 'p1', 'relative/path'), /完整绝对路径/);
await assert.rejects(() => importImageDirectory(db, 'other-project', folder), /项目不存在/);
await assert.rejects(() => importImageDirectory(db, 'p1', path.join(root, 'missing')), /无法读取/);
await assert.rejects(() => importImageDirectory(db, 'p1', folder, AbortSignal.abort()), { name: 'AbortError' });
await fs.writeFile(path.join(folder, '图片20.png'), png.subarray(0, 100));
const beforeFiles = await fs.readdir(path.join(root, 'storage', 'originals', 'inputs'));
await assert.rejects(() => importImageDirectory(db, 'p1', folder), /图片损坏/);
assert.equal((db.prepare('SELECT COUNT(*) AS n FROM image_assets').get() as { n: number }).n, 3, '部分失败不能留下数据库行');
assert.deepEqual(await fs.readdir(path.join(root, 'storage', 'originals', 'inputs')), beforeFiles, '部分失败清理本次副本');

await fs.unlink(path.join(folder, '图片20.png'));
const longPath = path.join(folder, '长详情.jpg');
await sharp({ create: { width: 1200, height: 9000, channels: 3, background: '#abcdef' } }).jpeg().toFile(longPath);
const again = await importImageDirectory(db, 'p1', folder);
const long = again.files.find((file) => file.filename === '长详情.jpg')!;
const slices = await tileSourceImages(db, 'p1', [long.id], { directVision: true });
assert.equal(slices.totalTiles, 3);
assert.ok(slices.pages[0]!.tiles.every((tile) => tile.width === 1200 && tile.height <= 4096));
db.close();
console.log('script-studio-import-directory.test.ts: ok');
